import{useEffect,useState}from'react';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://127.0.0.1:8000';
type Proposal={source_annotation_id?:string;source_polyline_id?:string;landmark_type?:string;original_coordinate?:number[];candidate_tooth_instance_ids:string[];selected_tooth_instance_id?:string|null;selected_tooth_instance_ids?:string[];ambiguity_status:string;uncertainty_reason?:string|null;provenance_label:string};
type Data={original_image:{width:number;height:number};tooth_instances:Array<{tooth_instance_id:string}>;landmark_proposals:Proposal[];bone_line_proposals:Proposal[];corrections:Array<{source_annotation_id:string;decision:string}>};
export default function AssociationReviewPanel({imageId,imageSrc,onBack}:{imageId:string;imageSrc:string;onBack:()=>void}){
 const[partition,setPartition]=useState('Validation'),[data,setData]=useState<Data|null>(null),[index,setIndex]=useState(0),[tooth,setTooth]=useState(''),[reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState('Not saved');
 useEffect(()=>{fetch(`${API}/api/stage2b/associations/${partition}/${encodeURIComponent(imageId)}`).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail);return r.json()}).then((x:Data)=>{setData(x);setIndex(0);setError('')}).catch(e=>setError(String(e)))},[imageId,partition]);
 const findings=data?[...data.landmark_proposals,...data.bone_line_proposals]:[],finding=findings[index],id=finding?.source_annotation_id||finding?.source_polyline_id||'',reviewed=new Set(data?.corrections.map(x=>x.source_annotation_id)||[]);
 useEffect(()=>{if(finding)setTooth(finding.selected_tooth_instance_id||finding.selected_tooth_instance_ids?.[0]||finding.candidate_tooth_instance_ids?.[0]||'')},[finding]);
 async function decide(decision:string){if(!finding)return;if(!reviewer.trim())return setError('Enter an anonymous reviewer ID.');if((decision==='reject'||decision==='uncertain')&&!reason.trim())return setError('Enter a reason for this decision.');setSaved('Saving…');const r=await fetch(`${API}/api/stage2b/associations/${partition}/${imageId}/corrections`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewer_id:reviewer,source_annotation_id:id,decision,selected_tooth_instance_id:decision==='reassign'||decision==='accept'?tooth||null:null,uncertainty_reason:reason||null,raw_proposal:finding})}),x=await r.json();if(!r.ok){setSaved('Save failed');return setError(x.detail||'Save failed')}setData({...data!,corrections:[...data!.corrections,x]});setSaved('Saved');setReason('');setError('');const next=findings.findIndex((f,n)=>n>index&&!reviewed.has(f.source_annotation_id||f.source_polyline_id||''));if(next>=0)setIndex(next)}
 return <section className="legacy-association"><header className="module-heading"><div><span className="eyebrow">LEGACY ASSOCIATION REVIEW</span><h2>Review one anatomical finding</h2><p>Use Stage 2C Pilot v2 for the current supervised workflow.</p></div><button onClick={onBack}>Back to case</button></header><div className="module-toolbar"><label>Partition<select value={partition} onChange={e=>setPartition(e.target.value)}><option>Training</option><option>Validation</option></select></label><label>Anonymous reviewer ID<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><span>{saved}</span></div>{error&&<p className="save-error" role="alert">{error}</p>}{data&&finding&&<><div className="finding-progress"><strong>Finding {index+1} of {findings.length}</strong><span>{reviewed.size} reviewed</span></div><div className="association-workspace"><div className="association-image"><img src={imageSrc} alt="Radiograph for association review"/>{finding.original_coordinate&&<svg viewBox={`0 0 ${data.original_image.width} ${data.original_image.height}`}><circle cx={finding.original_coordinate[0]} cy={finding.original_coordinate[1]} r="9"/></svg>}</div><aside><h3>{finding.landmark_type==='cej'?'CEJ landmark':finding.landmark_type==='apex'?'Root apex landmark':'Bone line'}</h3><p>Does this finding belong to the selected tooth?</p><label>Selected tooth<select value={tooth} onChange={e=>setTooth(e.target.value)}><option value="">Choose…</option>{data.tooth_instances.map((t,i)=><option key={t.tooth_instance_id} value={t.tooth_instance_id}>Tooth {i+1}</option>)}</select></label><label>Reason for rejection or uncertainty<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="decision-buttons"><button disabled={!tooth} onClick={()=>void decide('accept')}>Correct</button><button disabled={!tooth} onClick={()=>void decide('reassign')}>Assign to selected tooth</button><button onClick={()=>void decide('reject')}>Incorrect</button><button onClick={()=>void decide('not_visible')}>Not visible</button><button onClick={()=>void decide('uncertain')}>Uncertain</button><button onClick={()=>void decide('not_applicable')}>Not applicable</button></div><details><summary>Technical details</summary><p>{id}</p><p>{finding.ambiguity_status}</p></details></aside></div><footer className="module-nav"><button disabled={!index} onClick={()=>setIndex(index-1)}>Previous finding</button><button disabled={index===findings.length-1} onClick={()=>setIndex(index+1)}>Next finding</button></footer></>}</section>
}
