import {useEffect,useState} from 'react';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://127.0.0.1:8000';
type Entry={pilot_case_id:string;file_name:string;age:number};
export default function GroundTruthPilotPanel({onExit}:{onExit:()=>void}){
 const [entries,setEntries]=useState<Entry[]>([]),[index,setIndex]=useState(0),[reviewer,setReviewer]=useState('reviewer_A'),[done,setDone]=useState<string[]>([]),[message,setMessage]=useState('');
 const [quality,setQuality]=useState('acceptable'),[fdi,setFdi]=useState('11'),[surface,setSurface]=useState('mesial'),[level,setLevel]=useState('not_assessable'),[notes,setNotes]=useState('');
 const [cejX,setCejX]=useState(''),[cejY,setCejY]=useState(''),[crestX,setCrestX]=useState(''),[crestY,setCrestY]=useState(''),[apexX,setApexX]=useState(''),[apexY,setApexY]=useState(''),[loss,setLoss]=useState('');
 useEffect(()=>{fetch(`${API}/api/ground-truth-pilot/manifest`).then(r=>r.ok?r.json():Promise.reject()).then(x=>setEntries(x.entries||[])).catch(()=>setMessage('BRAR pilot unavailable. Restart the backend.'));},[]);
 useEffect(()=>{fetch(`${API}/api/ground-truth-pilot/status/${reviewer}`).then(r=>r.json()).then(x=>setDone(x.completed_case_ids||[])).catch(()=>setDone([]));},[reviewer,message]);
 const current=entries[index], brar=current&&loss?Number(loss)/current.age:null;
 function reset(){setQuality('acceptable');setFdi('11');setSurface('mesial');setLevel('not_assessable');setNotes('');setCejX('');setCejY('');setCrestX('');setCrestY('');setApexX('');setApexY('');setLoss('');setMessage('');}
 async function lock(){if(!current)return;const assessable=level!=='not_assessable';const point=(x:string,y:string)=>assessable?{x:Number(x),y:Number(y)}:null;const payload={protocol_version:'1.0',pilot_case_id:current.pilot_case_id,anonymous_reviewer_id:reviewer,image_quality:quality,maximum_loss_fdi:assessable?fdi:null,maximum_loss_surface:assessable?surface:null,cej:point(cejX,cejY),alveolar_crest:point(crestX,crestY),apex:point(apexX,apexY),bone_loss_percent:assessable?Number(loss):null,reviewer_brar:assessable?brar:null,reviewer_level:assessable?Number(level):'not_assessable',notes,completed_at_utc:new Date().toISOString()};const r=await fetch(`${API}/api/ground-truth-pilot/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));setMessage(r.ok?'Review locked. Published label remained hidden.':typeof b.detail==='string'?b.detail:'Complete all required measurement fields.');}
 const fdis=Array.from({length:32},(_,i)=>`${Math.floor(i/8)+1}${i%8+1}`);
 return <main className="gt-pilot"><header className="gt-header"><div><span className="eyebrow">BLINDED BRAR PILOT</span><h1>BRAR label verification</h1></div><label>Reviewer<select value={reviewer} onChange={e=>{setReviewer(e.target.value);reset();}}><option>reviewer_A</option><option>reviewer_B</option></select></label><span>{done.length}/{entries.length} locked</span><button onClick={onExit}>Exit</button></header>
 {!current?<section className="gt-card">{message||'Loading...'}</section>:<><section className="gt-context"><button disabled={!index} onClick={()=>{setIndex(index-1);reset();}}>Previous</button><div><strong>{current.pilot_case_id}</strong><span>Age {current.age} · {index+1} of {entries.length} {done.includes(current.pilot_case_id)?'· Locked':''}</span></div><button disabled={index===entries.length-1} onClick={()=>{setIndex(index+1);reset();}}>Next</button></section>
 <section className="gt-workspace"><div className="gt-image"><img src={`${API}/api/ground-truth-pilot/cases/${current.pilot_case_id}/image`} alt={current.pilot_case_id}/></div><aside className="gt-card"><p className="notice">Published BRAR measurement and level are hidden. Identify the single tooth/site with maximum radiographic loss.</p><label>Image quality<select value={quality} onChange={e=>setQuality(e.target.value)}><option>acceptable</option><option>suboptimal</option><option>unreadable</option></select></label><label>Maximum-loss FDI<select value={fdi} onChange={e=>setFdi(e.target.value)}>{fdis.map(x=><option key={x}>{x}</option>)}</select></label><label>Surface<select value={surface} onChange={e=>setSurface(e.target.value)}><option>mesial</option><option>distal</option></select></label>
 {([['CEJ',cejX,setCejX,cejY,setCejY],['Alveolar crest',crestX,setCrestX,crestY,setCrestY],['Apex',apexX,setApexX,apexY,setApexY]] as const).map(([name,x,sx,y,sy])=><fieldset className="gt-point" key={name}><legend>{name}</legend><label>x<input type="number" min="0" value={x} onChange={e=>sx(e.target.value)}/></label><label>y<input type="number" min="0" value={y} onChange={e=>sy(e.target.value)}/></label></fieldset>)}
 <label>Bone loss %<input type="number" min="0" max="100" step="0.1" value={loss} onChange={e=>setLoss(e.target.value)}/></label><div className="notice">Calculated BRAR: <strong>{brar===null?'—':brar.toFixed(3)}</strong> (bone-loss % ÷ age)</div><label>Reviewer level<select value={level} onChange={e=>setLevel(e.target.value)}><option value="not_assessable">not assessable</option><option value="1">Level 1 (&lt;0.25)</option><option value="2">Level 2 (0.25–1.0)</option><option value="3">Level 3 (&gt;1.0)</option></select></label><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{message&&<p role="status">{message}</p>}<button className="primary-action" disabled={done.includes(current.pilot_case_id)} onClick={()=>void lock()}>Lock independent review</button></aside></section></>}</main>;
}
