import {useEffect, useMemo, useState} from 'react';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://127.0.0.1:8000';
const questions=[['cej_correct','Is the CEJ landmark correctly placed?'],['bone_level_correct','Is the bone-level landmark correctly placed for RBL measurement?'],['root_landmark_appropriate','Is the selected root landmark/apex appropriate?'],['mesial_distal_association_correct','Are mesial and distal landmark associations correct?'],['geometry_clinically_plausible','Is the CEJ → bone level → root geometry clinically plausible?'],['surface_assessable','Is this surface assessable from the radiograph?']] as const;
const answers=['','yes','no','uncertain','not_applicable'] as const;
type Answer=typeof answers[number]; type Entry={case_id:string;root_class:string}; type Surface='mesial'|'distal';
type Form={answers:Record<(typeof questions)[number][0],Answer>;reasons:string[];comments:string};
const blank=():Form=>({answers:Object.fromEntries(questions.map(([key])=>[key,''])) as Form['answers'],reasons:[],comments:''});
export default function PerioKptExpertReviewPanel({onExit}:{onExit:()=>void}){
 const [entries,setEntries]=useState<Entry[]>([]),[reasons,setReasons]=useState<string[]>([]),[index,setIndex]=useState(0),[reviewer,setReviewer]=useState('reviewer_A'),[done,setDone]=useState<string[]>([]),[message,setMessage]=useState('');
 const [forms,setForms]=useState<Record<Surface,Form>>({mesial:blank(),distal:blank()}); const current=entries[index],locked=Boolean(current&&done.includes(current.case_id));
 useEffect(()=>{fetch(`${API}/api/perio-kpt-expert-review/manifest`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setEntries(data.cases||[]);setReasons(data.reason_codes||[]);}).catch(()=>setMessage('The Perio-KPT review package is unavailable. Start or restart the backend.'));},[]);
 useEffect(()=>{if(!/^[A-Za-z0-9_-]{1,64}$/.test(reviewer)){setDone([]);return;}fetch(`${API}/api/perio-kpt-expert-review/status/${reviewer}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>setDone(data.completed_case_ids||[])).catch(()=>setDone([]));},[reviewer,message]);
 const complete=useMemo(()=>Object.values(forms).every(form=>questions.every(([key])=>form.answers[key]!=='')),[forms]);
 function reset(){setForms({mesial:blank(),distal:blank()});setMessage('');}
 function setAnswer(surface:Surface,key:(typeof questions)[number][0],value:Answer){setForms(old=>({...old,[surface]:{...old[surface],answers:{...old[surface].answers,[key]:value}}}));}
 function toggleReason(surface:Surface,reason:string){setForms(old=>{const before=old[surface].reasons;return {...old,[surface]:{...old[surface],reasons:before.includes(reason)?before.filter(x=>x!==reason):[...before,reason]}};});}
 async function lock(){if(!current||!complete)return;const payload={protocol_version:'1.0',case_id:current.case_id,anonymous_reviewer_id:reviewer,completed_at_utc:new Date().toISOString(),surfaces:(['mesial','distal'] as Surface[]).map(surface=>({surface,...forms[surface].answers,reason_codes:forms[surface].reasons,comments:forms[surface].comments}))};const response=await fetch(`${API}/api/perio-kpt-expert-review/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));setMessage(response.ok?'Review locked. Source labels and the blinding key remain unchanged.':typeof body.detail==='string'?body.detail:Array.isArray(body.detail)?body.detail.map((x:{msg?:string})=>x.msg).join(' '):'Review could not be saved.');}
 return <main className="kpt-review"><header className="kpt-review-header"><div><span className="eyebrow">BLINDED EXPERT REVIEW</span><h1>Perio-KPT landmark verification</h1></div><label>Anonymous reviewer ID<input value={reviewer} onChange={e=>{setReviewer(e.target.value);reset();}}/></label><span className="save-chip">{done.length}/{entries.length} locked</span><button onClick={onExit}>Exit</button></header>{!current?<section className="kpt-review-card">{message||'Loading review cases…'}</section>:<><section className="kpt-review-context"><button disabled={!index} onClick={()=>{setIndex(index-1);reset();}}>Previous</button><div><strong>{current.case_id}</strong><span>{current.root_class.replace('_',' ')} · {index+1} of {entries.length} {locked?'· Locked':''}</span></div><button disabled={index===entries.length-1} onClick={()=>{setIndex(index+1);reset();}}>Next</button></section><section className="kpt-review-workspace"><figure className="kpt-review-image"><img src={`${API}/api/perio-kpt-expert-review/cases/${current.case_id}/image`} alt={`Ground-truth landmark overlay for ${current.case_id}`}/><figcaption>Green points are existing ground-truth landmarks. Review placement only.</figcaption></figure><aside className="kpt-review-form"><div className="research-disclaimer"><strong>Research audit only.</strong> Do not diagnose disease, assign severity, or modify the source annotation.</div>{(['mesial','distal'] as Surface[]).map(surface=><fieldset className="kpt-surface" key={surface} disabled={locked}><legend>{surface} surface</legend>{questions.map(([key,label])=><label key={key}>{label}<select value={forms[surface].answers[key]} onChange={e=>setAnswer(surface,key,e.target.value as Answer)}><option value="">Choose…</option><option value="yes">Yes</option><option value="no">No</option><option value="uncertain">Uncertain</option><option value="not_applicable">Not applicable</option></select></label>)}<details><summary>Reason codes (required for “no” or “uncertain”)</summary><div className="kpt-reasons">{reasons.map(reason=><label key={reason}><input type="checkbox" checked={forms[surface].reasons.includes(reason)} onChange={()=>toggleReason(surface,reason)}/>{reason.replace(/_/g,' ')}</label>)}</div></details><label>Comments<textarea value={forms[surface].comments} onChange={e=>setForms(old=>({...old,[surface]:{...old[surface],comments:e.target.value}}))}/></label></fieldset>)}{message&&<p role="status" className={message.includes('could not')?'save-error':'notice'}>{message}</p>}<button className="primary-action" disabled={locked||!complete||!/^[A-Za-z0-9_-]{1,64}$/.test(reviewer)} onClick={()=>void lock()}>{locked?'Review locked':'Lock completed case review'}</button></aside></section></>}</main>;
}
