import{useEffect,useMemo,useState,type PointerEvent}from'react';
import{caseStatus,findingId,findingName,nextUnreviewed,reviewedIds}from'./stage2cUx.js';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://127.0.0.1:8000';
type Entry={source_partition:'Training'|'Validation';source_image_id:string;stable_image_id:string;primary_selection_reason:string;uncertainty_stratum:string;review_count:number};
type Tooth={tooth_instance_id:string;expanded_crop_box_xyxy:number[]};
type Proposal={source_annotation_id?:string;source_polyline_id?:string;landmark_type?:'cej'|'apex';original_coordinate?:number[];original_points?:number[][];candidate_tooth_instance_ids:string[];selected_tooth_instance_id?:string|null;association_confidence?:number;confidence?:number;ambiguity_status:string;uncertainty_reason?:string|null};
type Action={action_id:string;version:number;reviewer_id:string;action:string;source_annotation_id?:string;point?:number[];review_state:string};
type Data={original_image:{width:number;height:number};tooth_instances:Tooth[];landmark_proposals:Proposal[];bone_line_proposals:Proposal[];expert_actions:Action[]};
type Decision=''|'correct'|'needs_correction'|'cannot';type Setup={arch:string;side:string;orientation:string;flip:string};

export default function PilotReviewPanel({onExit}:{onExit?:()=>void}){
 const[queue,setQueue]=useState<Entry[]>([]),[index,setIndex]=useState(0),[data,setData]=useState<Data|null>(null),[reviewer,setReviewer]=useState(''),[findingIndex,setFindingIndex]=useState(0),[tooth,setTooth]=useState(''),[decision,setDecision]=useState<Decision>(''),[reason,setReason]=useState(''),[note,setNote]=useState(''),[editMode,setEditMode]=useState<''|'move'|'reassign'|'add'|'bone'>(''),[draft,setDraft]=useState<{x:number;y:number}|null>(null),[secondTooth,setSecondTooth]=useState(''),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[dashboard,setDashboard]=useState(true),[saved,setSaved]=useState('Not saved'),[error,setError]=useState(''),[help,setHelp]=useState(false),[setup,setSetup]=useState<Setup>({arch:'',side:'',orientation:'',flip:''});
 const entry=queue[index],findings=useMemo(()=>data?[...data.landmark_proposals,...data.bone_line_proposals]:[],[data]),selected=findings[findingIndex],done=reviewedIds(data?.expert_actions||[]),setupReady=Object.values(setup).every(Boolean);
 useEffect(()=>{fetch(`${API}/api/stage2c/queue`).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail);return r.json()}).then(x=>setQueue(x.entries)).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!entry||dashboard)return;fetch(`${API}/api/stage2c/associations/${entry.source_partition}/${entry.source_image_id}`).then(r=>r.json()).then((x:Data)=>{setData(x);setFindingIndex(Math.max(0,nextUnreviewed([...x.landmark_proposals,...x.bone_line_proposals],x.expert_actions)));setDecision('');setEditMode('');setDraft(null);setSetup({arch:'',side:'',orientation:'',flip:''});setSaved('Loaded')}).catch(e=>setError(String(e)))},[entry,dashboard]);
 useEffect(()=>{if(!selected)return;setTooth(selected.selected_tooth_instance_id||selected.candidate_tooth_instance_ids?.[0]||'');setDecision('');setEditMode('');setDraft(null);setReason('');setNote('');setZoom(1);setPan({x:0,y:0})},[selected]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(draft||note||reason){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[draft,note,reason]);
 const resetFinding=(n:number)=>{setFindingIndex(n);setDecision('');setEditMode('');setDraft(null);setError('')};
 async function submit(body:Record<string,unknown>){if(!entry||!data||!reviewer.trim())return setError('Enter your anonymous reviewer ID.');setSaved('Saving…');const r=await fetch(`${API}/api/stage2c/associations/${entry.source_partition}/${entry.source_image_id}/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewer_id:reviewer,partition:entry.source_partition,expert_note:note,...body})}),result=await r.json();if(!r.ok){setSaved('Save failed');return setError(result.detail||'Save failed')}setData({...data,expert_actions:[...data.expert_actions,result]});setSaved('Saved just now');setError('');const n=nextUnreviewed(findings,[...data.expert_actions,result],findingIndex);if(n>=0)resetFinding(n);return result}
 function base(action:string,state:string,extra:Record<string,unknown>={}){if(!selected)return;void submit({source_annotation_id:findingId(selected),tooth_instance_id:tooth||null,action,finding_type:selected.landmark_type||'bone_line',review_state:state,selected_tooth_instance_ids:tooth?[tooth]:[],uncertainty_reason:reason||null,...extra})}
 function chooseCorrect(){if(!tooth)return setError('Select the tooth for this finding first.');base('accept','expert_confirmed')}
 function markState(state:'uncertain'|'not_visible'|'not_applicable'|'needs_second_review'){if(!reason.trim())return setError('Enter a reason before saving this decision.');base('mark_state',state==='needs_second_review'?'needs_second_review':state==='uncertain'?'uncertain':'expert_corrected',{landmark_state:state==='needs_second_review'?'uncertain':state})}
 function point(e:PointerEvent<SVGSVGElement>){const svg=e.currentTarget,p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM()!.inverse());if(q.x>=0&&q.y>=0&&data&&q.x<data.original_image.width&&q.y<data.original_image.height)setDraft({x:q.x,y:q.y})}
 function saveCorrection(){if(!selected)return;if(!reason.trim())return setError('Enter a reason before saving a correction.');if(editMode==='move'&&draft)base('move','expert_corrected',{point:[draft.x,draft.y],landmark_state:'visible'});else if(editMode==='reassign')base('reassign','expert_corrected');else if(editMode==='bone')base('assign_bone_scope','expert_corrected',{bone_scope:secondTooth?'interproximal_pair':'one_tooth_surface',selected_tooth_instance_ids:secondTooth?[tooth,secondTooth]:[tooth]});else setError('Choose and complete a correction first.')}
 function remove(){if(selected&&reason.trim()&&confirm('Remove this finding from the expert correction? The original AI proposal remains unchanged.'))base('delete','expert_corrected');else if(!reason.trim())setError('Enter a reason before removing a finding.')}
 function addPoint(type:'cej'|'apex'){if(!draft||!tooth)return setError('Select a tooth and click the image to place the missing landmark.');void submit({source_annotation_id:null,tooth_instance_id:tooth,action:'add',finding_type:type,review_state:'expert_corrected',selected_tooth_instance_ids:[tooth],point:[draft.x,draft.y],landmark_state:'visible',uncertainty_reason:reason||null})}
 function leave(fn:()=>void){if(!(draft||note||reason)||confirm('Leave this finding? Unsaved edits and notes will be lost.'))fn()}
 if(!queue.length)return <main className="stage2c-shell"><h2>Stage 2C pilot v2</h2><p>{error||'Loading verified review queue…'}</p></main>;
 if(dashboard)return <main className="stage2c-shell"><Tutorial open={help} close={()=>setHelp(false)}/><Header reviewer={reviewer} setReviewer={setReviewer} saved="Dashboard" help={()=>setHelp(true)} exit={onExit}/><section className="stage2c-dashboard"><span className="eyebrow">EXPERT REVIEW QUEUE</span><h1>Stage 2C anatomical finding review</h1><p>Review AI-proposed anatomical findings. No diagnostic or model-performance metrics are shown.</p><button className="primary-action" disabled={!reviewer} onClick={()=>{const n=queue.findIndex(x=>!x.review_count);setIndex(n<0?0:n);setDashboard(false)}}>Resume next incomplete case</button><div className="stage2c-case-grid">{queue.map((x,i)=><button disabled={!reviewer} key={x.stable_image_id} onClick={()=>{setIndex(i);setDashboard(false)}}><strong>Case {i+1} of {queue.length}</strong><span>{x.source_partition}</span><span>{x.review_count?'In progress':'Not started'}</span></button>)}</div></section></main>;
 const view=data?`${pan.x} ${pan.y} ${data.original_image.width/zoom} ${data.original_image.height/zoom}`:'0 0 1 1',image=`${API}/api/stage2c/images/${entry.source_partition}/${entry.source_image_id}`,nextFinding=data?nextUnreviewed(findings,data.expert_actions,findingIndex):-1;
 return <main className="stage2c-shell"><Tutorial open={help} close={()=>setHelp(false)}/><Header reviewer={reviewer} setReviewer={setReviewer} saved={saved} help={()=>setHelp(true)} exit={()=>leave(onExit||(()=>setDashboard(true)))}/><section className="stage2c-context"><div><strong>Case {index+1} of {queue.length}</strong><span>{caseStatus(findings,data?.expert_actions||[])}</span></div><div><strong>Finding {findingIndex+1} of {findings.length}</strong><span>{done.size} reviewed · {Math.max(0,findings.length-done.size)} remaining</span></div><button onClick={()=>leave(()=>setDashboard(true))}>Dashboard</button></section>
 {!setupReady&&<section className="stage2c-setup"><h2>Confirm viewing context</h2><p>Complete this orientation check before reviewing anatomical findings.</p><label>Arch<select value={setup.arch} onChange={e=>setSetup({...setup,arch:e.target.value})}><option value="">Choose…</option><option>Maxillary</option><option>Mandibular</option></select></label><label>Patient side<select value={setup.side} onChange={e=>setSetup({...setup,side:e.target.value})}><option value="">Choose…</option><option>Left</option><option>Right</option><option>Anterior</option></select></label><label>Display orientation<select value={setup.orientation} onChange={e=>setSetup({...setup,orientation:e.target.value})}><option value="">Choose…</option><option>Native</option><option>Mirrored</option><option>Rotated</option></select></label><label>Horizontally flipped?<select value={setup.flip} onChange={e=>setSetup({...setup,flip:e.target.value})}><option value="">Choose…</option><option>No</option><option>Yes</option></select></label></section>}
 {data&&selected&&<><section className="stage2c-instruction"><div><span className="eyebrow">CURRENT FINDING</span><h2>{findingName(selected)}</h2><p>Confirm that the highlighted finding belongs to the selected tooth and is correctly positioned.</p></div><div className="finding-legend"><span><i className="raw-dot"/>Original AI position</span><span><i className="draft-dot"/>Unsaved correction</span><span><i className="saved-dot"/>Saved review</span></div></section><section className="stage2c-workspace"><div className="stage2c-viewer"><div className="viewer-commandbar"><button onClick={()=>setZoom(v=>Math.min(4,v+.25))}>Zoom +</button><button onClick={()=>setZoom(v=>Math.max(1,v-.25))}>Zoom −</button><button onClick={()=>setPan(p=>({...p,x:p.x-30/zoom}))}>← Pan</button><button onClick={()=>setPan(p=>({...p,x:p.x+30/zoom}))}>Pan →</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Reset</button><span>{Math.round(zoom*100)}%</span></div>{editMode==='move'&&<div className="active-tool">Click the image to reposition this landmark.</div>}{editMode==='add'&&<div className="active-tool">Click the image to place a missing landmark.</div>}<svg viewBox={view} onPointerDown={editMode==='move'||editMode==='add'?point:undefined}><image href={image} width={data.original_image.width} height={data.original_image.height}/>{selected.original_coordinate&&<><circle cx={selected.original_coordinate[0]} cy={selected.original_coordinate[1]} r="10" className="stage2c-raw"/><circle cx={(draft?.x??selected.original_coordinate[0])} cy={(draft?.y??selected.original_coordinate[1])} r="7" className={draft?'stage2c-draft':'stage2c-current'}/></>}{selected.original_points&&<polyline points={selected.original_points.map(x=>x.join(',')).join(' ')} className="stage2c-line"/>}</svg><details><summary>Technical details</summary><p>Finding ID: {findingId(selected)}</p><p>Internal tooth ID: {tooth||'unassigned'}</p><p>Case selection category: {entry.primary_selection_reason}</p></details></div>
 <aside className="stage2c-decision"><label>Selected tooth<select value={tooth} onChange={e=>setTooth(e.target.value)}><option value="">Choose a tooth…</option>{data.tooth_instances.map((t,i)=><option value={t.tooth_instance_id} key={t.tooth_instance_id}>Tooth {i+1}</option>)}</select></label>{tooth&&<img className="stage2c-mask" alt="Selected tooth mask" src={`${API}/api/stage2c/masks/${entry.source_partition}/${entry.source_image_id}/${encodeURIComponent(tooth)}`}/>}<h3>Is this finding correct for this tooth?</h3><div className="decision-buttons"><button className={decision==='correct'?'selected':''} disabled={!setupReady} onClick={()=>{setDecision('correct');chooseCorrect()}}>Correct</button><button className={decision==='needs_correction'?'selected':''} disabled={!setupReady} onClick={()=>setDecision('needs_correction')}>Needs correction</button><button className={decision==='cannot'?'selected':''} disabled={!setupReady} onClick={()=>setDecision('cannot')}>Cannot determine</button></div>
 {decision==='needs_correction'&&<section className="progressive-actions"><h4>Choose a correction</h4>{selected.original_coordinate&&<button onClick={()=>setEditMode('move')}>Reposition point</button>}<button onClick={()=>setEditMode('reassign')}>Assign to another tooth</button>{selected.original_points&&<button onClick={()=>setEditMode('bone')}>Set bone-line ownership</button>}<button onClick={()=>setEditMode('add')}>Add a missing landmark</button><button className="danger-action" onClick={remove}>Remove this finding</button>{editMode==='bone'&&<label>Second neighboring tooth (optional)<select value={secondTooth} onChange={e=>setSecondTooth(e.target.value)}><option value="">This tooth surface only</option>{data.tooth_instances.filter(t=>t.tooth_instance_id!==tooth).map((t,i)=><option key={t.tooth_instance_id} value={t.tooth_instance_id}>Neighboring tooth {i+1}</option>)}</select></label>}{editMode==='add'&&<div className="two-actions"><button disabled={!draft} onClick={()=>addPoint('cej')}>Save as CEJ</button><button disabled={!draft} onClick={()=>addPoint('apex')}>Save as apex</button></div>}{editMode&&editMode!=='add'&&<div className="two-actions"><button className="primary-action" onClick={saveCorrection}>Save correction</button><button onClick={()=>{setEditMode('');setDraft(null)}}>Cancel</button></div>}</section>}
 {decision==='cannot'&&<section className="progressive-actions"><p>Choose the most accurate status.</p><button onClick={()=>markState('not_visible')}>Not visible</button><button onClick={()=>markState('uncertain')}>Uncertain</button><button onClick={()=>markState('not_applicable')}>Not applicable</button><button onClick={()=>markState('needs_second_review')}>Needs second review</button></section>}
 {(decision==='needs_correction'||decision==='cannot')&&<><label>Reason (required)<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Briefly explain the decision"/></label><label>Reviewer note (optional)<textarea value={note} onChange={e=>setNote(e.target.value)}/></label></>}{error&&<p className="save-error" role="alert">{error}</p>}</aside></section></>}
 <footer className="stage2c-nav"><button disabled={!findingIndex} onClick={()=>leave(()=>resetFinding(findingIndex-1))}>Previous finding</button><button disabled={nextFinding<0} onClick={()=>leave(()=>resetFinding(nextFinding))}>Next incomplete finding</button><button disabled={index===queue.length-1} onClick={()=>leave(()=>setIndex(index+1))}>Next case</button></footer></main>
}
function Header({reviewer,setReviewer,saved,help,exit}:{reviewer:string;setReviewer:(v:string)=>void;saved:string;help:()=>void;exit?:()=>void}){return <header className="stage2c-header"><div><span className="eyebrow">STAGE 2C PILOT V2</span><strong>Anatomical finding review</strong></div><label>Anonymous reviewer ID<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><span className="save-chip">{saved}</span><button onClick={help}>Help</button>{exit&&<button onClick={exit}>Exit</button>}</header>}
function Tutorial({open,close}:{open:boolean;close:()=>void}){if(!open)return null;return <div className="tutorial-backdrop"><section className="tutorial-dialog" role="dialog" aria-modal="true" aria-labelledby="s2-help"><span className="eyebrow">QUICK GUIDE</span><h2 id="s2-help">Review one finding at a time</h2><ol><li>Confirm the viewing context.</li><li>Select the tooth that owns the highlighted finding.</li><li>Choose Correct, Needs correction, or Cannot determine.</li><li>Save a correction or status, then continue to the next incomplete finding.</li></ol><p>The outlined marker is the immutable AI proposal. Corrections create new expert versions; they never overwrite the raw proposal.</p><p>This workflow reviews anatomical associations only. It does not collect diagnosis, severity, treatment, or bone-loss percentage.</p><button className="primary-action" onClick={close}>Start review</button></section></div>}
