import {useEffect,useMemo,useState,type MouseEvent,type ReactNode} from 'react';
import {markerX,swapSurfaceRecords} from './surfaceVerification.js';
import {PILOT_STEPS,stepComplete} from './pilotUx.js';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://localhost:8000';
type Point={x:number;y:number}; type Kind='cej'|'bone_crest'|'root_apex';
type Landmark={landmark_id:string|null;state:string;point:Point|null;verification_status:string;expert_notes:string};
type Surface={surface:'mesial'|'distal';pixel_side:'image_left'|'image_right'|null;adjacent_fdi:string|null;adjacency_status:string;verification_status:string;expert_decision:string;review_notes:string;cej:Landmark;bone_crest:Landmark;root_apex:Landmark;model_cej:Point|null;model_bone_crest:Point|null;model_root_apex:Point|null;rbl_percentage?:number|null;cej_to_bone_distance_px?:number|null;cej_to_apex_distance_px?:number|null;apex_reference_id:string|null;apex_selection_method:string};
type Tooth={tooth_instance_id:string;reference_mask_path:string;original_bbox_xyxy:number[];centroid:Point;expert_fdi:string|null;tooth_verification_status:string;surfaces:Surface[]};
const landmarkBlank=():Landmark=>({landmark_id:null,state:'uncertain',point:null,verification_status:'unverified',expert_notes:''});
const surfaceBlank=():Surface[]=>(['mesial','distal'] as const).map(surface=>({surface,pixel_side:null,adjacent_fdi:null,adjacency_status:'unverified',verification_status:'unverified',expert_decision:'pending',review_notes:'',cej:landmarkBlank(),bone_crest:landmarkBlank(),root_apex:landmarkBlank(),model_cej:null,model_bone_crest:null,model_root_apex:null,apex_reference_id:null,apex_selection_method:'not_selected'}));
const help=[['Confirm image orientation','Set the arch, patient side, display orientation, and flip state.','This establishes the patient-based frame used by every later decision.'],['Confirm tooth identity','Select each tooth, enter its FDI number, and confirm it.','Identity must be established before mesial and distal can be interpreted safely.'],['Verify mesial and distal','Assign image side and adjacent tooth for both surfaces.','Mesial and distal are anatomical surfaces, not fixed screen directions.'],['Place the CEJ','Place or adjust the CEJ on each surface.','The CEJ is one endpoint of the bone-loss measurement.'],['Place the bone crest','Place or adjust the alveolar crest.','This identifies the measured crestal level.'],['Confirm the root apex','Place the apex and record its reference.','The apex supplies the root-length reference for normalized RBL.'],['Review and save','Review checks, notes, and measurements before saving.','Warnings are quality checks, not diagnoses.']];

export default function SurfaceVerificationPanel({imageId,imageSrc,onBack,expertId='',onSaved}:{imageId:string;imageSrc:string;onBack:()=>void;expertId?:string;onSaved?:()=>void}){
 const[partition]=useState<'Training'|'Validation'>('Training'),[proposal,setProposal]=useState<any>(),[teeth,setTeeth]=useState<Tooth[]>([]),[localExpert,setLocalExpert]=useState(''),[orientation,setOrientation]=useState<any>({arch:'unknown',patient_side:'unknown',display_orientation:'unknown',horizontal_flip:null,source:'unknown',status:'unverified',verified_by:null,verified_at:null});
 const[step,setStep]=useState(0),[ti,setTi]=useState(0),[si,setSi]=useState(0),[tool,setTool]=useState<{t:number;s:number;k:Kind}|null>(null),[history,setHistory]=useState<{t:number;s:number;k:Kind;before:Landmark}[]>([]),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[warnings,setWarnings]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
 const expert=expertId||localExpert, tooth=teeth[ti], surface=tooth?.surfaces[si];
 const complete=useMemo(()=>PILOT_STEPS.map((x:any)=>stepComplete(x.id,orientation,teeth)),[orientation,teeth]);
 useEffect(()=>{fetch(`${API}/api/surface-verification/${partition}/${imageId}`).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail);return r.json()}).then(d=>{setProposal(d.proposal);setTeeth(d.proposal.teeth.map((t:Tooth)=>({...t,surfaces:surfaceBlank()})));setDirty(false);setError('')}).catch(e=>setError(String(e.message||e)))},[imageId,partition]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 function mark(){setDirty(true);setMessage('Unsaved changes')}
 function editTooth(i:number,c:Partial<Tooth>){setTeeth(v=>v.map((x,n)=>n===i?{...x,...c}:x));mark()}
 function editSurface(t:number,s:number,c:Partial<Surface>){setTeeth(v=>v.map((x,n)=>{if(n!==t)return x;const a=[...x.surfaces];a[s]={...a[s],...c};return{...x,surfaces:a}}));mark()}
 function editLandmark(t:number,s:number,k:Kind,c:Partial<Landmark>){setTeeth(v=>v.map((x,n)=>{if(n!==t)return x;const a=[...x.surfaces],old=a[s];a[s]={...old,[k]:{...old[k],...c}};return{...x,surfaces:a}}));mark()}
 function undo(){const x=history[history.length-1];if(!x)return;editLandmark(x.t,x.s,x.k,x.before);setHistory(v=>v.slice(0,-1));setTool(null)}
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.key==='Escape')setTool(null);else if(e.key==='+'||e.key==='=')setZoom(v=>Math.min(4,v+.25));else if(e.key==='-')setZoom(v=>Math.max(1,v-.25))};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)});
 function place(e:MouseEvent<SVGSVGElement>){if(!tool)return;const p=e.currentTarget.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(e.currentTarget.getScreenCTM()!.inverse()),before=teeth[tool.t].surfaces[tool.s][tool.k];setHistory(v=>[...v,{...tool,before:{...before,point:before.point&&{...before.point}}}]);editLandmark(tool.t,tool.s,tool.k,{landmark_id:`expert:${tool.k}`,state:'visible',point:{x:q.x,y:q.y},verification_status:'unverified'});setTool(null)}
 function confirmOrientation(){if(!expert||['arch','patient_side','display_orientation'].some(k=>orientation[k]==='unknown')||orientation.horizontal_flip===null)return setError('Complete every orientation field and the expert ID.');setOrientation({...orientation,status:'verified',source:'expert_confirmation',verified_by:expert,verified_at:new Date().toISOString()});setError('');mark()}
 async function save(){setSaving(true);try{const body={reviewer_id:expert,partition,image_id:imageId,orientation,teeth:teeth.map(t=>({instance_id:t.tooth_instance_id,original_instance_id:t.tooth_instance_id,original_mask_ref:t.reference_mask_path,original_bbox_xyxy:t.original_bbox_xyxy,centroid:t.centroid,model_fdi_suggestion:null,expert_fdi:t.expert_fdi||null,tooth_verification_status:t.tooth_verification_status,fdi_source:t.tooth_verification_status==='confirmed'?'expert_confirmation':'none',surfaces:t.surfaces}))},r=await fetch(`${API}/api/surface-verification/${partition}/${imageId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)return setError(d.detail||'Save failed');setWarnings(d.warnings);setTeeth(v=>v.map((t,i)=>({...t,surfaces:d.teeth[i].surfaces})));setDirty(false);setMessage(`Saved versioned review with ${d.warnings.length} warning(s).`);onSaved?.()}finally{setSaving(false)}}
 const kind:Kind=step===3?'cej':step===4?'bone_crest':'root_apex',view=proposal?`${pan.x} ${pan.y} ${proposal.original_image.width/zoom} ${proposal.original_image.height/zoom}`:'0 0 1 1';
 return <section className="surface-review guided-review">
  <nav className="review-stepper" aria-label="Annotation steps">{PILOT_STEPS.map((x:any,i:number)=><button key={x[0]||i} className={i===step?'active':complete[i]?'complete':''} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}><span>{complete[i]?'✓':i+1}</span>{x.label}</button>)}</nav>
  <section className="step-guidance"><div><span className="eyebrow">STEP {step+1} OF 7</span><h2>{help[step][0]}</h2><p>{help[step][1]}</p></div><p><strong>Why:</strong> {help[step][2]}</p></section>
  {proposal&&<div className="guided-layout"><section className="image-workspace" aria-label="Radiograph annotation viewer"><div className="viewer-commandbar"><button onClick={()=>setZoom(v=>Math.min(4,v+.25))}>Zoom +</button><button onClick={()=>setZoom(v=>Math.max(1,v-.25))}>Zoom −</button><button onClick={()=>setPan(p=>({...p,x:p.x-30/zoom}))}>← Pan</button><button onClick={()=>setPan(p=>({...p,x:p.x+30/zoom}))}>Pan →</button><button onClick={()=>setPan(p=>({...p,y:p.y-30/zoom}))}>↑ Pan</button><button onClick={()=>setPan(p=>({...p,y:p.y+30/zoom}))}>Pan ↓</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Reset</button><button disabled={!history.length} onClick={undo}>Undo</button><span>{Math.round(zoom*100)}%</span></div>{tool&&<div className="active-tool" role="status">Click the image to place {tool.k.replace('_',' ')}. Esc cancels.</div>}<svg viewBox={view} onClick={place} className={tool?'placing-landmark':''}><image href={`${imageSrc}${imageSrc.includes("?")?"&":"?"}v=raw-radiograph`} width={proposal.original_image.width} height={proposal.original_image.height}/>{teeth.map((t,n)=><g key={t.tooth_instance_id} className={n===ti?'selected-tooth':''}><rect onClick={e=>{if(!tool){e.stopPropagation();setTi(n)}}} x={t.original_bbox_xyxy[0]} y={t.original_bbox_xyxy[1]} width={t.original_bbox_xyxy[2]-t.original_bbox_xyxy[0]} height={t.original_bbox_xyxy[3]-t.original_bbox_xyxy[1]} className="surface-box"/><text x={t.original_bbox_xyxy[0]} y={t.original_bbox_xyxy[1]-8} className="surface-label">{n+1} · {t.expert_fdi||'FDI ?'}</text>{t.surfaces.map(s=><g key={s.surface}>{s.pixel_side&&<text x={markerX(t.original_bbox_xyxy,s.pixel_side)} y={(t.original_bbox_xyxy[1]+t.original_bbox_xyxy[3])/2} className="surface-marker">{s.surface[0].toUpperCase()}</text>}{s.cej.point&&s.bone_crest.point&&<line x1={s.cej.point.x} y1={s.cej.point.y} x2={s.bone_crest.point.x} y2={s.bone_crest.point.y} className="measurement-line"/>}{[s.cej,s.bone_crest,s.root_apex].map((l,j)=>l.point&&<circle key={j} cx={l.point.x} cy={l.point.y} r="7" className={`expert-point ${l.verification_status}`}/>)}</g>)}</g>)}</svg></section>
   <aside className="step-controls">{!expertId&&<label>Expert ID<input value={localExpert} onChange={e=>setLocalExpert(e.target.value)}/></label>}{step===0&&<OrientationControls value={orientation} update={(c:any)=>{setOrientation({...orientation,...c,status:'unverified'});mark()}} confirm={confirmOrientation}/>} {step>0&&<><label>Tooth<select value={ti} onChange={e=>setTi(Number(e.target.value))}>{teeth.map((t,i)=><option value={i} key={t.tooth_instance_id}>Tooth {i+1} — {t.expert_fdi||'FDI unconfirmed'}</option>)}</select></label>{step>1&&<div className="segmented"><button className={si===0?'selected':''} onClick={()=>setSi(0)}>Mesial</button><button className={si===1?'selected':''} onClick={()=>setSi(1)}>Distal</button></div>}</>}
   {step===1&&tooth&&<><label>FDI tooth number<input inputMode="numeric" value={tooth.expert_fdi||''} onChange={e=>editTooth(ti,{expert_fdi:e.target.value})}/></label><button onClick={()=>editTooth(ti,{tooth_verification_status:'confirmed'})}>Confirm tooth identity</button><small>Status: {tooth.tooth_verification_status}</small></>}
   {step===2&&surface&&<><label>Image side<select value={surface.pixel_side||''} onChange={e=>editSurface(ti,si,{pixel_side:(e.target.value||null) as any})}><option value="">Choose…</option><option value="image_left">Image left</option><option value="image_right">Image right</option></select></label><label>Adjacent FDI<input value={surface.adjacent_fdi||''} onChange={e=>editSurface(ti,si,{adjacent_fdi:e.target.value||null})}/></label><button onClick={()=>editSurface(ti,si,{verification_status:'confirmed',expert_decision:'confirmed',adjacency_status:'verified'})}>Confirm {surface.surface}</button><button onClick={()=>editTooth(ti,{surfaces:swapSurfaceRecords(tooth.surfaces)})}>Swap M/D assignments</button><button onClick={()=>confirm('Mark this surface ungradable?')&&editSurface(ti,si,{verification_status:'ungradable',expert_decision:'ungradable'})}>Mark ungradable</button></>}
   {step>=3&&step<=5&&surface&&<LandmarkEditor kind={kind} value={surface[kind]} place={()=>setTool({t:ti,s:si,k:kind})} update={c=>editLandmark(ti,si,kind,c)}>{step===5&&<label>Apex reference<input value={surface.apex_reference_id||''} onChange={e=>editSurface(ti,si,{apex_reference_id:e.target.value||null,apex_selection_method:e.target.value?'expert_selected':'not_selected'})}/></label>}</LandmarkEditor>}
   {step===6&&<><h3>Review summary</h3><p>{complete.filter(Boolean).length} of 7 steps complete</p>{teeth.map((t,i)=><div className="review-row" key={t.tooth_instance_id}><strong>{t.expert_fdi||`Tooth ${i+1}`}</strong><span>{t.surfaces.filter(s=>s.verification_status==='confirmed').length}/2 surfaces confirmed</span></div>)}<button className="primary-action" disabled={!expert||saving} onClick={()=>void save()}>{saving?'Saving…':'Save versioned review'}</button></>}
   </aside></div>}
  {warnings.length>0&&<div className="geometry-warnings" role="alert"><strong>Quality checks need attention</strong>{warnings.map((w,i)=><p className={w.severity==='block'?'invalid-measurement':''} key={i}>{warningText(w.code,w.message)}</p>)}<details><summary>Technical details</summary><pre>{JSON.stringify(warnings,null,2)}</pre></details></div>}{error&&<div className="save-error" role="alert">{error}</div>}{message&&<div className="notice teal" role="status">{message}</div>}
  <footer className="step-actions"><button onClick={step?()=>setStep(step-1):()=>{if(!dirty||confirm('Leave and discard unsaved changes?'))onBack()}}>{step?'Back':'Return to dashboard'}</button><button disabled={!dirty||saving||!expert} onClick={()=>void save()}>Save progress</button><button className="primary-action" disabled={!complete[step]||step===6} onClick={()=>setStep(step+1)}>Continue</button></footer>
 </section>
}
function OrientationControls({value,update,confirm}:{value:any;update:(v:any)=>void;confirm:()=>void}){return <><label>Dataset partition<select aria-label="Dataset partition" value="Training" disabled><option>Training</option></select></label>{['arch','patient_side','display_orientation'].map(key=><label key={key}>{key.replace('_',' ')}<select value={value[key]} onChange={e=>update({[key]:e.target.value})}><option value="unknown">Choose…</option>{(key==='arch'?['maxillary','mandibular']:key==='patient_side'?['left','right','anterior']:['native','mirrored','rotated']).map(x=><option key={x}>{x}</option>)}</select></label>)}<label>Horizontally flipped?<select value={value.horizontal_flip===null?'':String(value.horizontal_flip)} onChange={e=>update({horizontal_flip:e.target.value===''?null:e.target.value==='true'})}><option value="">Choose…</option><option value="false">No</option><option value="true">Yes</option></select></label><button className="primary-action" onClick={confirm}>Confirm orientation</button><small>Status: {value.status}</small></>}
function LandmarkEditor({kind,value,place,update,children}:{kind:Kind;value:Landmark;place:()=>void;update:(c:Partial<Landmark>)=>void;children?:ReactNode}){return <><h3>{kind.replace('_',' ')}</h3><p>{value.point?`Placed at ${value.point.x.toFixed(1)}, ${value.point.y.toFixed(1)}`:value.state==='not_visible'?'Marked not visible':'No point placed'}</p><button className="primary-action" onClick={place}>{value.point?'Reposition':'Place'} landmark</button><button disabled={!value.point} onClick={()=>update({verification_status:'confirmed'})}>Confirm placement</button><button onClick={()=>confirm('Record this landmark as not visible?')&&update({state:'not_visible',point:null,verification_status:'unverified'})}>Not visible</button><label>Landmark notes<textarea value={value.expert_notes} onChange={e=>update({expert_notes:e.target.value})}/></label>{children}</>}
function warningText(code:string,message:string){return({missing_landmark:'A required landmark is missing.',invalid_measurement:'The landmark order produces an invalid measurement.',surface_identity_unverified:'Mesial or distal identity has not been confirmed.',orientation_unverified:'Image orientation has not been confirmed.'} as Record<string,string>)[code]||message}
