import {useEffect,useState} from 'react';
import SurfaceVerificationPanel from './SurfaceVerificationPanel';
import ExpertTutorial from './ExpertTutorial';
import {caseLabel,finishTutorial,nextIncomplete,tutorialComplete} from './pilotUx.js';
const API=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')||'http://localhost:8000';
type Entry={pilot_case_id:string;source_image_id:string;arch:string;site:string};

export default function SurfacePilotPanel({onExit,initialSourceImageId}:{onExit:()=>void;initialSourceImageId?:string}){
 const[entries,setEntries]=useState<Entry[]>([]),[states,setStates]=useState<any[]>([]),[index,setIndex]=useState(0),[expert,setExpert]=useState(''),[state,setState]=useState<any>(null),[dashboard,setDashboard]=useState(true),[tutorial,setTutorial]=useState(()=>!tutorialComplete(localStorage,'anonymous')),[started,setStarted]=useState(''),[saveStatus,setSaveStatus]=useState('Not saved'),[decision,setDecision]=useState('accept'),[notes,setNotes]=useState(''),[error,setError]=useState(''),[feedback,setFeedback]=useState(false);const current=entries[index];
 useEffect(()=>{fetch(`${API}/api/surface-pilot/manifest`).then(r=>r.json()).then(x=>setEntries(x.entries)).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!initialSourceImageId||!entries.length)return;const selected=entries.findIndex(x=>x.source_image_id===initialSourceImageId);if(selected>=0)setIndex(selected);else setError('This image is not part of the frozen Unified Anatomical Review manifest.')},[entries,initialSourceImageId]);
 useEffect(()=>{if(initialSourceImageId&&expert&&current?.source_image_id===initialSourceImageId)setDashboard(false)},[current,expert,initialSourceImageId]);
 useEffect(()=>{if(!current||!expert)return;fetch(`${API}/api/surface-pilot/cases/${current.pilot_case_id}/${expert}`).then(r=>r.json()).then(setState).catch(e=>setError(String(e)))},[current,expert]);
 useEffect(()=>{if(!entries.length||!expert)return;Promise.all(entries.map(x=>fetch(`${API}/api/surface-pilot/cases/${x.pilot_case_id}/${expert}`).then(r=>r.json()))).then(setStates).catch(e=>setError(String(e)))},[entries,expert,state?.phase_a_locked,state?.phase_b]);
 async function post(path:string,body:any){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){setError(d.detail||'Request failed');return null;}setError('');return d;}
 async function session(action:string){if(!expert)return setError('Enter an anonymous expert ID.');if(action==='complete'&&!confirm('Complete this case? Confirm that your saved review is finished.'))return;if(action==='start'&&!started)setStarted(new Date().toISOString());await post(`/api/surface-pilot/cases/${current.pilot_case_id}/session`,{anonymous_expert_id:expert,action,notes});setSaveStatus(action==='pause'?'Paused':action==='resume'?'Resumed':'Session saved');}
 async function lock(){if(!confirm('Lock Phase A? The independent annotation cannot be edited afterward.'))return;const d=await post(`/api/surface-pilot/cases/${current.pilot_case_id}/lock-existing-surface-record`,{anonymous_expert_id:expert,started_at:started||new Date().toISOString(),counters:{},technical_issues:[]});if(d){setState({...state,phase_a_locked:true,phase_a:d});setSaveStatus('Phase A locked');}}
 async function reveal(){if(!confirm('Reveal Stage 2C suggestions for this same case after locking Phase A? Phase A remains unchanged.'))return;const d=await post(`/api/surface-pilot/cases/${current.pilot_case_id}/${expert}/reveal`,{});if(d)setState({...state,model_revealed:true,model_snapshot:d});}
 async function assisted(){const d=await post(`/api/surface-pilot/cases/${current.pilot_case_id}/phase-b`,{anonymous_expert_id:expert,decision,notes,assisted_correction:null,started_at:new Date().toISOString()});if(d){setState({...state,phase_b:d});setSaveStatus('Assisted review saved');}}
 async function issue(){const description=prompt('Describe the technical problem');if(description)await post(`/api/surface-pilot/cases/${current.pilot_case_id}/issues`,{anonymous_expert_id:expert,description,severity:'minor'});}
 const finishHelp=()=>{finishTutorial(localStorage,expert||'anonymous');setTutorial(false)};
 if(!current)return <main className="content"><h2>Unified anatomical review</h2><p>{error||'Loading frozen manifest…'}</p></main>;
 if(dashboard)return <main className="pilot-shell"><ExpertTutorial open={tutorial} onClose={()=>setTutorial(false)} onFinish={finishHelp}/><header className="pilot-persistent"><div><span className="eyebrow">SUPERVISED DENTAL-EXPERT PILOT</span><h1>Radiographic surface review</h1></div><label>Anonymous expert ID<input aria-label="Anonymous expert ID" value={expert} onChange={e=>setExpert(e.target.value)}/></label><button onClick={()=>setTutorial(true)}>Help / Tutorial</button><button onClick={onExit}>Exit</button></header><section className="pilot-dashboard"><h2>Your 20 Training cases</h2><p>No model-performance or agreement metrics are displayed.</p><button className="primary-action" disabled={!expert||!states.length} onClick={()=>{const n=nextIncomplete(states);setIndex(n<0?0:n);setDashboard(false)}}>Resume next incomplete case</button><div className="dashboard-grid">{entries.map((x,i)=><button key={x.pilot_case_id} className="case-status-card" disabled={!expert} onClick={()=>{setIndex(i);setDashboard(false)}}><strong>Case {i+1} of {entries.length}</strong><span>{x.arch} · {x.site}</span><span>{caseLabel(states[i])}</span></button>)}</div></section></main>;
 return <main className="pilot-shell"><ExpertTutorial open={tutorial} onClose={()=>setTutorial(false)} onFinish={finishHelp}/><header className="pilot-persistent"><div><span className="eyebrow">SURFACE PILOT V1</span><strong>Case {index+1} of {entries.length}</strong></div><div className="pilot-header-status"><span>{expert}</span><span>{state?.phase_a_locked?'Assisted Review':'Independent Review'}</span><span>{saveStatus}</span></div><button onClick={()=>setTutorial(true)}>Help / Tutorial</button><button onClick={()=>void session('pause')}>Pause</button><button onClick={()=>setDashboard(true)}>Dashboard</button><button onClick={onExit}>Exit</button></header><section className="case-context"><div><h1>{current.pilot_case_id}</h1><p>{current.arch} · {current.site}</p></div><progress aria-label="Overall pilot progress" max={entries.length} value={index+1}/></section><nav className="pilot-session-controls" aria-label="Review controls"><button onClick={()=>void session('start')}>Start</button><button onClick={()=>void session('resume')}>Resume</button><button onClick={()=>void session('complete')}>Complete case</button><button onClick={()=>void issue()}>Report technical problem</button><button onClick={()=>setFeedback(true)}>Final feedback</button></nav>{error&&<p className="save-error" role="alert">{error}</p>}
 {!state?.phase_a_locked?<><div className="audit-warning"><strong>Phase A — independent review.</strong> Model information remains hidden. Complete the guided steps, save, then lock.</div><SurfaceVerificationPanel expertId={expert} onSaved={()=>setSaveStatus('Review saved')} imageId={current.source_image_id} imageSrc={`${API}/api/surface-pilot/cases/${current.pilot_case_id}/image`} onBack={()=>setDashboard(true)}/><button className="irreversible-action" onClick={()=>void lock()}>Submit and lock Phase A</button></>:<><div className="notice teal">Phase A is locked and immutable.</div>{!state.model_revealed?<button className="primary-action" onClick={()=>void reveal()}>Reveal model results for Phase B</button>:<section className="assisted-review"><h2>Phase B — assisted comparison</h2><p>Compare with your locked independent review. Records remain separate.</p><details><summary>Technical model details</summary><pre className="pilot-model-json">{JSON.stringify(state.model_snapshot?.model_output,null,2)}</pre></details><label>Is the model suggestion acceptable?<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="acceptable">Acceptable</option><option value="partially_acceptable">Partially acceptable</option><option value="not_acceptable">Not acceptable</option><option value="ungradable">Ungradable</option></select></label><label>Assisted-review notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary-action" disabled={!!state.phase_b} onClick={()=>void assisted()}>Submit assisted review</button></section>}</>}
 <footer className="pilot-case-nav"><button disabled={!index} onClick={()=>setIndex(index-1)}>Back: previous case</button><button disabled={index===entries.length-1} onClick={()=>setIndex(index+1)}>Next case</button></footer>{feedback&&<Feedback expert={expert} close={()=>setFeedback(false)}/>}</main>;
}
function Feedback({expert,close}:{expert:string;close:()=>void}){const keys=['orientation','fdi','mesial_distal','cej','bone_crest','apex','warnings','rbl','usability','clinical_usefulness'],[ratings,setRatings]=useState<Record<string,number>>(Object.fromEntries(keys.map(k=>[k,3]))),[answers,setAnswers]=useState<Record<string,string>>({most_difficult:'',unclear_labels:'',incorrect_warnings:'',improvements:'',decision_support_useful:''}),[done,setDone]=useState(false);async function submit(){const r=await fetch(`${API}/api/surface-pilot/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({anonymous_expert_id:expert,ratings,...answers})});setDone(r.ok)}return <section className="pilot-feedback" role="dialog" aria-modal="true" aria-labelledby="feedback-title"><h2 id="feedback-title">Pilot feedback</h2>{keys.map(k=><label key={k}>{k.replace(/_/g,' ')}<select value={ratings[k]} onChange={e=>setRatings({...ratings,[k]:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label>)}{Object.keys(answers).map(k=><label key={k}>{k.replace(/_/g,' ')}<textarea value={answers[k]} onChange={e=>setAnswers({...answers,[k]:e.target.value})}/></label>)}<button disabled={!expert||done} onClick={()=>void submit()}>{done?'Feedback saved':'Submit feedback'}</button><button onClick={close}>Close</button></section>}
