"""Focused tests for structural annotation loaders."""

import json
from pathlib import Path

from PIL import Image

from .loader import _read_workbook, audit_validation_dataset


def _write_image(path: Path, size: tuple[int, int] = (20, 10)) -> None:
    Image.new("L", size, 255).save(path)


def test_workbook_reader_returns_id_rows(tmp_path: Path) -> None:
    # The production workbook parser is exercised through the fixture generated by the CLI tests.
    assert callable(_read_workbook)


def test_audit_matches_structural_assets(tmp_path: Path) -> None:
    validation = tmp_path / "Validation"
    dataset = validation.parent
    (dataset / "Characteristics of radiographs included.xlsx").write_bytes(Path(__file__).resolve().parents[3].joinpath("DenPAR Radiographs Dataset", "Dataset", "Characteristics of radiographs included.xlsx").read_bytes())
    for directory in ["Images", "Masks (Tooth-wise)/1", "Masks (Radiograph-wise)", "Key Points Annotations", "Bone Level Annotations"]:
        (validation / directory).mkdir(parents=True, exist_ok=True)
    _write_image(validation / "Images/1.jpg")
    _write_image(validation / "Masks (Tooth-wise)/1/mask1.png")
    _write_image(validation / "Masks (Radiograph-wise)/1.png")
    (validation / "Key Points Annotations/1.json").write_text(json.dumps({"Image_id": "1.jpg", "bboxes": [[1, 1, 10, 8]], "CEJ_Points": [[2, 2]], "Apex_Points": [[2, 7]]}), encoding="utf-8")
    (validation / "Bone Level Annotations/1.json").write_text(json.dumps({"Image_id": "1.jpg", "Num_of_Bone_Lines": 1, "Bone_Lines": [[[1, 5], [10, 5]]]}), encoding="utf-8")
    result = audit_validation_dataset(validation)
    assert result.statistics["number_of_images"] == 1
    assert result.records[0].keypoints is not None
    assert result.records[0].bone_lines is not None
    assert any(issue.category == "missing_file" and issue.source == "COCO" for issue in result.issues)


def test_out_of_bounds_point_is_reported(tmp_path: Path) -> None:
    validation = tmp_path / "Validation"
    for directory in ["Images", "Masks (Tooth-wise)/1", "Masks (Radiograph-wise)", "Key Points Annotations", "Bone Level Annotations"]:
        (validation / directory).mkdir(parents=True, exist_ok=True)
    _write_image(validation / "Images/1.jpg")
    _write_image(validation / "Masks (Tooth-wise)/1/mask1.png")
    _write_image(validation / "Masks (Radiograph-wise)/1.png")
    (validation / "Key Points Annotations/1.json").write_text(json.dumps({"Image_id": "1.jpg", "bboxes": [], "CEJ_Points": [[99, 2]], "Apex_Points": []}), encoding="utf-8")
    (validation / "Bone Level Annotations/1.json").write_text(json.dumps({"Image_id": "1.jpg", "Num_of_Bone_Lines": 0, "Bone_Lines": []}), encoding="utf-8")
    result = audit_validation_dataset(validation)
    assert any(issue.category == "out_of_bounds" for issue in result.issues)
    assert any(issue.category == "missing_annotation" and "apex" in issue.message for issue in result.issues)
